'use client'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from '@/components/app.header';
import AppFooter from '@/components/app.footer';
import Container from 'react-bootstrap/Container';
import AppSider from '@/components/app.sider';
import { Breadcrumb, Layout, Menu, theme } from 'antd';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Next 13</title>
      </head>
      <body className={inter.className}>
        <Layout style={{ minHeight: '100vh' }}>
          <AppHeader />

          <Layout style={{ minHeight: '80vh' }}>
            <AppSider />
            <Layout>
              {children}
              <AppFooter />
            </Layout>
          </Layout>
        </Layout>
      </body>
    </html >
  )
}
